name: Publish
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  release-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: intemd
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: intemd/ytmusic-api

      - name: Push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            intemd/ytmusic-api:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
